# Generated by Django 3.2.3 on 2022-02-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('generos', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='opcao',
            options={'verbose_name_plural': 'Opções'},
        ),
        migrations.AddField(
            model_name='pergunta',
            name='data_encerramento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='enquetes'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('perguntas', models.ManyToManyField(to='enquetes.Pergunta')),
            ],
        ),
    ]
