# Generated by Django 3.2.3 on 2022-02-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_auto_20220224_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='rotulo',
            options={'verbose_name_plural': 'Rótulos'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='rotulo',
            name='perguntas',
        ),
        migrations.AddField(
            model_name='autor',
            name='genero',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enquetes.autor'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='rotulos',
            field=models.ManyToManyField(to='enquetes.Rotulo'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
