# Generated by Django 3.2.3 on 2022-02-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('interesses', models.CharField(max_length=300)),
                ('data', models.DateField(auto_now_add=True)),
                ('contato', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=20)),
                ('imagem', models.ImageField(upload_to='')),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('anuncio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skambo.anuncio')),
                ('estado', models.IntegerField(choices=[(1, 'novo'), (2, 'semi-novo'), (3, 'usado'), (4, 'defeito')], default=1)),
                ('anos_de_uso', models.IntegerField()),
                ('marca', models.CharField(max_length=20)),
                ('categoria', models.IntegerField(choices=[(1, 'esporte'), (2, 'moveis'), (3, 'eletronicos'), (4, 'livros')], default=1)),
            ],
            bases=('skambo.anuncio',),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('anuncio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skambo.anuncio')),
                ('categoria', models.IntegerField(choices=[(1, 'beleza'), (2, 'contabilidade'), (3, 'educacao'), (4, 'design'), (5, 'informatica')], default=1)),
            ],
            bases=('skambo.anuncio',),
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.CharField(max_length=200)),
                ('data', models.DateField(auto_now_add=True)),
                ('aceita', models.BooleanField()),
                ('imagem', models.ImageField(upload_to='')),
                ('data_da_troca', models.DateField(null=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skambo.anuncio')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skambo.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='anunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skambo.usuario'),
        ),
    ]
