# Generated by Django 3.2.3 on 2022-02-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skambo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'esporte'), (2, 'moveis'), (3, 'eletronicos'), (4, 'livros'), (5, 'beleza')], default=1),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='imagem',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
