# Generated by Django 3.2.3 on 2022-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skambo', '0002_auto_20220217_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='imagem',
            field=models.ImageField(upload_to='media'),
        ),
    ]
