# Generated by Django 3.2.3 on 2022-02-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skambo', '0003_auto_20220217_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='slug',
        ),
    ]
