# Generated by Django 3.2.3 on 2022-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skambo', '0007_alter_usuario_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='anuncio',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='oferta',
        ),
        migrations.AlterField(
            model_name='proposta',
            name='aceita',
            field=models.BooleanField(null=True),
        ),
    ]
