# Generated by Django 3.2.3 on 2022-03-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skambo', '0008_auto_20220309_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='data_da_troca',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='proponente',
        ),
        migrations.AddField(
            model_name='proposta',
            name='anuncio_ofertado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to='skambo.anuncio'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='anuncio_proposto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_enviadas', to='skambo.anuncio'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('anuncio_desejado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_recebidas', to='skambo.anuncio')),
                ('anuncio_proposto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_envidas', to='skambo.anuncio')),
            ],
        ),
    ]
