# Generated by Django 3.2.3 on 2022-03-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skambo', '0009_auto_20220310_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='anuncio_ofertado',
        ),
    ]
