# Generated by Django 3.2.3 on 2022-03-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skambo', '0010_remove_proposta_anuncio_ofertado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='anuncio_desejado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to='skambo.anuncio'),
        ),
    ]
